### ISSUE TITLE
Assessing the Speed Advantage of FastV with KVCache in Comparison to LLaVa

### ISSUE THREAD

**Issue by hb-jw** [pkunlp-icler/FastV#22]
First of all, thank you for your excellent work. However, I noticed an issue: When using FastV with KVCache and comparing it to the original LLaVa (which uses full image tokens for inference) also using KVCache, does FastV still offer a speed advantage? In my own testing, I found that when both use KVCache, FastV has about the same inference speed as the original. The reason might be that, in this case, the query_states have a sequence length of only 1, and while FastV reduces the key_states and value_states along the seq_len dimension, CUDA’s underlying optimization of matrix multiplication minimizes the benefit. Therefore, I would like to ask if you have considered or tested this scenario? Thank you very much for your response.

**Comment by cool-xiang** [comment]
I also found a similar issue when using modeling_llama_fastv_kvcache.py. After generating the first token in the prefill stage, there is no longer any acceleration effect when generating subsequent tokens in the decoding stage.

**Comment by hb-jw** [comment]
Yes, my experimental results are similar. The acceleration occurs mainly during the prefill stage, while there is basically no acceleration during the decode stage. What are your thoughts on these results?

**Comment by chenllliang** [comment]
@hb-jw @cool-xiang Thanks for your attention. As mentioned in the [kv-cache](https://github.com/pkunlp-icler/FastV?tab=readme-ov-file#support-kv-cache) part, we also notice that the real acceleration decreases. This is because FastV reduces a fixed number of kv-cache tokens (256 tokens for llava), which is too short to leverage CUDA’s underlying optimization for the kv-cache.  The  acceleration  would be more significant if tested with longer visual tokens. Without kv-cache, FastV also decreases the time recomputing K,V values, while this part of acceleration is removed when kv-cache is enabled. The major acceleration of FastV when KV-Cache is enabled is from softmax and the MLP layer. However, the theoretical reduction in FLOPs remains the same since the selected caches are discarded, resulting in some memory reduction. I hope this helps!
