### ISSUE TITLE
 Reasons for the second forward in plot_efficient_attention.py

### ISSUE THREAD

**Issue by PhoenixZ810** [pkunlp-icler/FastV#23]
Hello! Thanks for your great contribution!
I have a question about the code in [plot_inefficient_attention.py](src/FastV/inference/plot_inefficient_attention.py):
```
model_output_ori, outputs_attention = inference(prompts, images, image_processor)
model_output,outputs_attention = inference(prompts,images,image_processor, append_output=model_output_ori[0])
```
I noticed that you use the complete conversation (both question and answer) for the second forward pass to obtain the final attention maps. **However, the output of the second forward pass seems to be nothing**. Could you please explain the reasoning behind this operation?

I would greatly appreciate your insight on this matter. Thank you!

**Comment by chenllliang** [comment]
Hi, this is because the output attention map only show the attention among input tokens according to huggingface's implementation, not included output tokens. If we also want to check how the output tokens attend to the input tokens, we need a double forward with the previous output added. The second inference would output nothing.
